/**
 * Created by Trubasa 1141521502@qq.com on 2018/9/26.
 */
// const path='F:/svn_project/project-goodOrder/wx_app/foodOrder'
const title = "配灯web版"
const path = 'F:\\maideng\\light-store'
const ruler = {
  qrCode:"生成二维码使用的插件",
  testJson:"测试时用到的一些数据静态数据",
  api:'网络请求全局处理方法',
  assets:"放一些通用的工具、样式、文件",
  "bus.js":"vue项目里，用于垮组件层级进行数据传递",
  "common.js":"可复用的一些方法",
  "myComponents.js":"用于注册自己编写的vue组件与页面",
  build:'开发、打包配置',
  config:'开发、打包配置',
  "index.js":"可配置开发模式的代理服务，实现前后端分离开发。配置打包后的文件名等。",
  src:'源码',
  components:"组件",
  pages:"页面",
  store:"Vuex的配置，管理全局变量",
  router:"vue-router的配置，管理spa的路由，可查看该文件确定所有页面的跳转路径与对应文件",
  "App.vue":"页面主文件，所有编写的页面代码最终通过该文件挂载到index.hml上",
  "main.js":"spa应用的主文件，在该文件里引入各种依赖",
  static:"静态资源目录",
  reset:"覆盖样式",
  "address.json":"地址选择的数据源",
  "SchemeEdit.vue":"方案编辑",
  ".vue":"",
  ".vue":"",
  ".vue":"",
  ".vue":"",
  ".vue":"",
  ".vue":"",
  ".vue":"",
  ".vue":"",
  ".vue":"",
  ".vue":"",
  ".vue":"",
  ".vue":"",
  ".vue":"",
  ".vue":"",
  ".vue":"",
  ".vue":"",
  ".vue":"",
  ".vue":"",
  ".vue":"",
  ".vue":"",
  ".vue":"",
  ".vue":"",
  ".vue":"",
  ".vue":"",
  ".vue":"",
  ".vue":"",
  ".vue":"",
  ".vue":"",
  ".vue":"",
  ".vue":"",
  ".vue":"",
  ".vue":"",
  ".vue":"",
  ".vue":"",
  ".vue":"",
  ".vue":"",
  ".vue":"",
}

module.exports = {
  title,
  path,
  ruler
}
