/**
 * Created by Trubasa 1141521502@qq.com on 2018/9/26.
 */
const ruler = {
  menu: '菜单页面',
  utils: '工具集，一些公用的方法都放在这里',
  templates: "模板,功能与组件类似，但偏重于显示，不包含太多处理逻辑",
  components: "组件",
  myDialog: "弹出框，2种样式 有黑色遮罩/没有黑色遮罩",
  appointmentItem: "预约单列表的每一个单独的预约单对象（废弃）",
  comboList: "点餐页面里，套餐的列表",
  comboListItem: "点餐页面里，套餐的列表每一项套餐",
  comboPanel: "点餐页面里，点击套餐后弹出的框",
  comboPanelItem: "点餐页面里，点击套餐后弹出的框的每一个分项",
  foodCart : "购物车组件，包括那个下单/预约的按钮也在这个组件里，点击按钮后提交时间到menu页面进行数据处理",
  foodCartComboItem : "购物车里显示所选套餐",
  foodCartItem : "购物车里显示所选单品",
  foodMenu : "菜牌组件，左侧为商品分类，右侧为商品列表",
  goodDetail  : "商品详情弹框",
  goodItem : "点餐页面里，商品列表里每个商品的对象",
  goodOrderShow : "订单确认和预约界面用户显示订单内容的组件",
  iconButton : "首页的图标按钮",
  listButton : "个人页的每项功能",
  moreTypeSelector : "选规格组件",
  myButton : "自定义按钮组件（基本没怎么用到）",
  classifyTop : "在swiperView里面，顶部的分类组件",
  myNumberSelector : "数量加减选择器",
  myPopupBottom : "弹出框，从下方弹出（没用到）",
  myPopupRight : "弹出框，从右方弹出，选择套菜内容的时候就有使用这个右侧弹出",
  myTitle : "标题组件，首页的'今日推荐'，菜单页面商品列表每项头的标题使用的组件",
  orderItem : "订单列表，每个订单项",
  personalProfile : "个人中心，个人信息的组件",
  recommendGoodItem : "首页推荐商品组件",
  rowView : "行组件，下单页面和预约页面有用来，用来规定一行的显示",
  scrollLoader : "滚动到底部加载更多数据",
  shoppingCart : "（废除）",
  shopProfile : "首页店铺信息组件",
  swiperView : "左右滑动切换组件",
  tabView : "（废除）",
  thisTable : "（废除）",
  truGetUserInfo : "判断用户是否有授权获取用户信息，没有的话则弹出是否确认授权",
  typeSelect : "商品规格、口味的选择组件",
  tabBar: "小程序下方的按钮图片",
  page: "页面",
  myOrder: "我的订单",
  home: "首页",
  appointment:'预订单',
  index:"无用文件",
  logs:"无用文件",
  pay:"买单",
  prePay:"订单确认",
  test:"无用文件",
  selectMenu:"无用文件",
  personal:"个人中心",
  pages:'页面',
  "project.config.json":'小程序开发配置文件',
  "api.js": '需要调用接口的一些方法，依赖common.js',
  "config.js": '配置项，存放接口地址等参数',
  "iconfont.wxss": 'iconfont字体图标',
  "common.js": '通用方法集',
  "order-item-tpl": '订单详情',
  "col-item": '（无用）',
  "listItem": '点餐页面商品列表里的商品展示',
  "dataTransform.js": '在数据提交、或者调用接口后，用于数据的转化',
  "netWork.js": '网络请求的方法，接口的全局处理等',
  "ext.json": '第三方开发时的配置文件'
}

module.exports = ruler
